"""Initial models

Revision ID: 7d944968d688
Revises: 
Create Date: 2026-10-01 19:42:59.886852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d944968d688'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('targets',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('repository', sa.String(), nullable=True),
    sa.Column('default_branch', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('authorized', sa.Boolean(), nullable=True),
    sa.Column('allowed_hosts', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_targets_project_id'), 'targets', ['project_id'], unique=False)
    op.create_table('assessments',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('assessment_type', sa.String(), nullable=False),
    sa.Column('profile', sa.String(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('files_scanned', sa.Integer(), nullable=True),
    sa.Column('tests_total', sa.Integer(), nullable=True),
    sa.Column('tests_completed', sa.Integer(), nullable=True),
    sa.Column('finding_count', sa.Integer(), nullable=True),
    sa.Column('confirmed_count', sa.Integer(), nullable=True),
    sa.Column('needs_review_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_project_id'), 'assessments', ['project_id'], unique=False)
    op.create_index(op.f('ix_assessments_target_id'), 'assessments', ['target_id'], unique=False)
    op.create_table('findings',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('component', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('context', sa.String(), nullable=True),
    sa.Column('cwe', sa.JSON(), nullable=True),
    sa.Column('owasp', sa.JSON(), nullable=True),
    sa.Column('cvss', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_assessment_id'), 'findings', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_findings_project_id'), 'findings', ['project_id'], unique=False)
    op.create_index(op.f('ix_findings_target_id'), 'findings', ['target_id'], unique=False)
    op.create_table('evidence',
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('snapshot_id', sa.String(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.Column('line_start', sa.Integer(), nullable=True),
    sa.Column('line_end', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('integrity_status', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_assessment_id'), 'evidence', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_evidence_finding_id'), 'evidence', ['finding_id'], unique=False)
    op.create_table('regression_tests',
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('expected_result', sa.String(), nullable=True),
    sa.Column('test_type', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regression_tests_assessment_id'), 'regression_tests', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_regression_tests_finding_id'), 'regression_tests', ['finding_id'], unique=False)
    op.create_table('remediations',
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('root_cause', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('implementation_guidance', sa.String(), nullable=True),
    sa.Column('validation_criteria', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediations_finding_id'), 'remediations', ['finding_id'], unique=False)
    op.create_table('validation_runs',
    sa.Column('finding_id', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('authorization_context', sa.String(), nullable=True),
    sa.Column('expected_result', sa.String(), nullable=True),
    sa.Column('observed_result', sa.String(), nullable=True),
    sa.Column('safety_checks', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_summary', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_runs_assessment_id'), 'validation_runs', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_finding_id'), 'validation_runs', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_runs_finding_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_assessment_id'), table_name='validation_runs')
    op.drop_table('validation_runs')
    op.drop_index(op.f('ix_remediations_finding_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_regression_tests_finding_id'), table_name='regression_tests')
    op.drop_index(op.f('ix_regression_tests_assessment_id'), table_name='regression_tests')
    op.drop_table('regression_tests')
    op.drop_index(op.f('ix_evidence_finding_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_assessment_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_findings_target_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_project_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_assessment_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_assessments_target_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_project_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_targets_project_id'), table_name='targets')
    op.drop_table('targets')
    op.drop_table('projects')
    # ### end Alembic commands ###
